<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Company></Company>
    <Product>WinKit</Product>
    <Authors>WinKit</Authors>
    <NeutralLanguage>en</NeutralLanguage>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugType>none</DebugType>
  </PropertyGroup>
</Project>
