<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Company></Company>
    <Product>WinKit</Product>
    <Authors>WinKit</Authors>
    <NeutralLanguage>en</NeutralLanguage>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
