using WinKit.Cleanup.Models;

namespace WinKit.Cleanup.Services;

public sealed class CleanupScanner : ICleanupScanner
{
    public Task<IReadOnlyList<CleanupCategoryScan>> ScanAsync(CancellationToken cancellationToken = default)
    {
        return Task.Run<IReadOnlyList<CleanupCategoryScan>>(() =>
        {
            var results = new List<CleanupCategoryScan>
            {
                ScanDirectory(
                    CleanupCategory.UserTemp,
                    "User temporary files",
                    "Temporary files created by apps running under your account.",
                    CleanupPaths.UserTemp),
                ScanDirectory(
                    CleanupCategory.WindowsTemp,
                    "Windows temporary files",
                    "Temporary files created by Windows and system processes.",
                    CleanupPaths.WindowsTemp),
                ScanThumbnailCache(),
                ScanRecycleBin(),
                ScanDirectory(
                    CleanupCategory.WindowsUpdateCache,
                    "Windows Update cache",
                    "Downloaded update packages that Windows Update no longer needs.",
                    CleanupPaths.WindowsUpdateDownloadCache)
            };

            cancellationToken.ThrowIfCancellationRequested();
            return results;
        }, cancellationToken);
    }

    private static CleanupCategoryScan ScanDirectory(
        CleanupCategory category, string displayName, string description, string path)
    {
        long size = 0;
        var count = 0;

        if (Directory.Exists(path))
        {
            foreach (var file in EnumerateFilesSafely(path))
            {
                try
                {
                    size += new FileInfo(file).Length;
                    count++;
                }
                catch (IOException)
                {
                    // File vanished or is locked; skip it for the size estimate.
                }
            }
        }

        return new CleanupCategoryScan
        {
            Category = category,
            DisplayName = displayName,
            Description = description,
            Locations = new[] { path },
            SizeBytes = size,
            FileCount = count
        };
    }

    private static CleanupCategoryScan ScanThumbnailCache()
    {
        var path = CleanupPaths.ExplorerCache;
        long size = 0;
        var count = 0;

        if (Directory.Exists(path))
        {
            foreach (var file in Directory.EnumerateFiles(path, "*.db", SearchOption.TopDirectoryOnly))
            {
                var name = Path.GetFileName(file);
                if (!name.StartsWith("thumbcache_", StringComparison.OrdinalIgnoreCase) &&
                    !name.StartsWith("iconcache_", StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                try
                {
                    size += new FileInfo(file).Length;
                    count++;
                }
                catch (IOException)
                {
                    // File vanished or is locked; skip it for the size estimate.
                }
            }
        }

        return new CleanupCategoryScan
        {
            Category = CleanupCategory.ThumbnailCache,
            DisplayName = "Thumbnail cache",
            Description = "Cached thumbnail and icon previews generated by File Explorer.",
            Locations = new[] { path },
            SizeBytes = size,
            FileCount = count
        };
    }

    private static CleanupCategoryScan ScanRecycleBin()
    {
        var (sizeBytes, itemCount) = RecycleBinInterop.Query();

        return new CleanupCategoryScan
        {
            Category = CleanupCategory.RecycleBin,
            DisplayName = "Recycle Bin",
            Description = "Files you've deleted that are still recoverable.",
            Locations = new[] { "Recycle Bin" },
            SizeBytes = sizeBytes,
            FileCount = (int)Math.Min(itemCount, int.MaxValue)
        };
    }

    private static IEnumerable<string> EnumerateFilesSafely(string path)
    {
        IEnumerator<string> enumerator;
        try
        {
            enumerator = Directory.EnumerateFiles(path, "*", CleanupPaths.SafeRecursiveEnumeration).GetEnumerator();
        }
        catch (UnauthorizedAccessException)
        {
            yield break;
        }
        catch (IOException)
        {
            yield break;
        }

        while (true)
        {
            string current;
            try
            {
                if (!enumerator.MoveNext())
                {
                    break;
                }

                current = enumerator.Current;
            }
            catch (UnauthorizedAccessException)
            {
                break;
            }
            catch (IOException)
            {
                break;
            }

            yield return current;
        }
    }
}
